// 1. 先导入 Vant 原生组件和自定义扩展组件
import * as Vant from "vant"; // 导入 Vant 所有原生组件
// 1.2. 必须引入 Vant 样式文件（关键！）
import 'vant/lib/index.css';
// 再引入自定义覆盖样式（注意顺序，后引入的会覆盖先引入的）
import '@/styles/vant-override.scss'
//2.
type VantComponentsType = typeof Vant & {};
// 3. 显式注解类型，避免 any 类型警告
const VantComponents: VantComponentsType = {
  ...Vant, // 全量继承 Vant 原生组件
};

export default VantComponents;

// //全局引入按需引入UI库vant
// import {
//   Col as VantCol,
//   Row as VantRow,
//   ActionBar as VantActionBar,
//   ActionBarIcon as VantActionBarIcon,
//   ActionBarButton as VantActionBarButton,
//   Divider as VantDivider,
//   Popup as VantPopup,
//   Overlay as VantOverlay,
//   Loading as VantLoading,
//   Dialog as VantDialog,
//   ContactCard as VantContactCard,
//   Form as VantForm,
//   AddressEdit as VantAddressEdit,
//   AddressList as VantAddressList,
//   Field as VantField,
//   CellGroup as VantCellGroup,
//   Cell as VantCell,
//   SwipeCell as VantSwipeCell,
//   Icon as VantIcon,
//   Image as VantImage,
//   Stepper as VantStepper,
//   Card as VantCard,
//   Checkbox as VantCheckbox,
//   CheckboxGroup as VantCheckboxGroup,
//   Button as VantButton,
//   Swipe as VantSwipe,
//   SwipeItem as VantSwipeItem,
//   PullRefresh as VantPullRefresh,
//   List as VantList,
//   Tab as VantTab,
//   Tabs as VantTabs,
//   SubmitBar as VantSubmitBar,
//   Toast as VantToast,
//   NumberKeyboard as VantNumberKeyboard,
//   Circle as VantCircle,
//   CountDown as VantCountDown,
//   Step as VantStep,
//   Steps as VantSteps,
//   Empty as VantEmpty,
//   Tabbar as VantTabbar,
//   TabbarItem as VantTabbarItem,
//   Pagination as VantPagination,
//   NoticeBar as VantNoticeBar,
//   IndexBar as VantIndexBar,
//   IndexAnchor as VantIndexAnchor,
//   Calendar as VantCalendar,
//   Picker as VantPicker,
//   Sidebar as VantSidebar,
//   SidebarItem as VantSidebarItem,
//   Grid as VantGrid,
//   GridItem as VantGridItem,
//   Popover as VantPopover,
//   DropdownMenu as VantDropdownMenu,
//   DropdownItem as VantDropdownItem,
//   Switch as VantSwitch,
//   RadioGroup as VantRadioGroup,
//   Radio as VantRadio,
//   Badge as VantBadge,
//   ActionSheet as VantActionSheet,
//   Area as VantArea,
//   Collapse as VantCollapse,
//   CollapseItem as VantCollapseItem,
//   TreeSelect as VantTreeSelect,
//   Lazyload as VantLazyload,
//   Tag as VantTag,
// } from 'vant';
// //全局引入样式
// import 'vant/es/button/style';
// import 'vant/es/icon/style';
// export {
//   VantCol,
//   VantRow,
//   VantActionBar,
//   VantActionBarIcon,
//   VantActionBarButton,
//   VantDivider,
//   VantPopup,
//   VantOverlay,
//   VantLoading,
//   VantDialog,
//   VantContactCard,
//   VantForm,
//   VantAddressEdit,
//   VantAddressList,
//   VantField,
//   VantCellGroup,
//   VantCell,
//   VantSwipeCell,
//   VantIcon,
//   VantImage,
//   VantStepper,
//   VantCard,
//   VantCheckbox,
//   VantCheckboxGroup,
//   VantButton,
//   VantSwipe,
//   VantSwipeItem,
//   VantPullRefresh,
//   VantList,
//   VantTab,
//   VantTabs,
//   VantSubmitBar,
//   VantToast,
//   VantNumberKeyboard,
//   VantCircle,
//   VantCountDown,
//   VantStep,
//   VantSteps,
//   VantEmpty,
//   VantTabbar,
//   VantTabbarItem,
//   VantPagination,
//   VantNoticeBar,
//   VantIndexBar,
//   VantIndexAnchor,
//   VantCalendar,
//   VantPicker,
//   VantSidebar,
//   VantSidebarItem,
//   VantGrid,
//   VantGridItem,
//   VantPopover,
//   VantDropdownMenu,
//   VantDropdownItem,
//   VantSwitch,
//   VantRadioGroup,
//   VantRadio,
//   VantBadge,
//   VantActionSheet,
//   VantArea,
//   VantCollapse,
//   VantCollapseItem,
//   VantTreeSelect,
//   VantLazyload,
//   VantTag,
// };
